### ISSUE TITLE
Application 'dojo' died in status LOADING_SOURCE_CODE: Cannot find module "."

### ISSUE THREAD

**Issue by VigneshRamamoorthy1992** [single-spa/single-spa-dojo#6] opened 2020-02-18 03:30 UTC
Hi Team,

i have tried using `single-spa-dojo` 

i'm getting this error 

![error](https://user-images.githubusercontent.com/31540363/74713872-6c3c3300-524f-11ea-826c-f80ae514d5a4.png)

sample code is available at
https://github.com/VigneshRamamoorthy1992/microfrontend/tree/master/react-angular-single-spa-master

index.js

```import singleSpaDojo from 'single-spa-dojo';
import App from './App.ts';
import { v, w } from '@dojo/framework/core/vdom';
import renderer from '@dojo/framework/core/vdom';
const dojoLifecycles = singleSpaDojo({
    renderer,
    v,
    w,
    appComponent: App,
    mountOptions: {
    }
})
export const bootstrap = props => dojoLifecycles.bootstrap(props)
export const mount = props => dojoLifecycles.mount(props)
export const unmount = props => dojoLifecycles.unmount(props)```

App.ts

import { WidgetBase } from '@dojo/framework/core/WidgetBase';
import { v, w } from '@dojo/framework/core/vdom';
export default class App extends WidgetBase {
	protected render() {
		return v('div', {}, ['App worked']);
	}
}

**Comment by filoxo** [comment] 2020-02-18 04:07
It would seem that this is a Webpack issue, since the error is at `webpackMissingModule`. A quick search found this issue https://github.com/webpack/webpack/issues/4921#issuecomment-342523044 which you might check as well.

**Comment by joeldenning** [comment] 2020-02-19 02:09
Sharing a screenshot of the webpack output in the terminal would be helpful, too

**Comment by VigneshRamamoorthy1992** [comment] 2020-02-19 02:19
> Sharing a screenshot of the webpack output in the terminal would be helpful, too

```> single-spa-example@ start C:\DRIVE-E\Project X\POCs\MicroFrontent\IvanJovMF\microfrontend\react-angular-single-spa-master
> webpack-dev-server --port 9090

clean-webpack-plugin: C:\DRIVE-E\Project X\POCs\MicroFrontent\IvanJovMF\microfrontend\react-angular-single-spa-master\dist has been removed.
Project is running at http://localhost:9090/
webpack output is served from /dist/
ts-loader: Using typescript@3.5.3 and C:\DRIVE-E\Project X\POCs\MicroFrontent\IvanJovMF\microfrontend\react-angular-single-spa-master\tsconfig.json
Hash: 0e14dceeb88136b65a06
Version: webpack 3.12.0
Time: 34957ms
                     Asset     Size  Chunks                    Chunk Names
                      0.js   229 kB       0  [emitted]
                      1.js   154 kB       1  [emitted]
                      2.js  17.9 kB       2  [emitted]
       root-application.js  28.2 kB       3  [emitted]         root-application
    common-dependencies.js  5.02 MB       4  [emitted]  [big]  common-dependencies
                  0.js.map   258 kB       0  [emitted]
                  1.js.map   177 kB       1  [emitted]
                  2.js.map  18.3 kB       2  [emitted]
   root-application.js.map  30.1 kB       3  [emitted]         root-application
common-dependencies.js.map  5.64 MB       4  [emitted]         common-dependencies
   [0] ./node_modules/tslib/tslib.es6.js 9.05 kB {4} [built]
   [1] ./node_modules/process/browser.js 5.42 kB {4} [built]
  [39] ./node_modules/@angular/core/fesm5/core.js 1.24 MB {4} [built]
  [71] ./node_modules/@angular/common/fesm5/common.js 264 kB {4} [built]
 [108] (webpack)-dev-server/client?http://localhost:9090 7.93 kB {4} [built]
 [142] ./node_modules/@angular/compiler/fesm5/compiler.js 1.31 MB {4} [built]
 [174] ./node_modules/react/react.js 56 bytes {4} [built]
 [175] ./node_modules/react-dom/index.js 59 bytes {4} [built]
 [176] ./node_modules/reflect-metadata/Reflect.js 51.2 kB {4} [built]
 [177] ./node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js 21 kB {4} [built]
 [178] ./node_modules/@angular/router/fesm5/router.js 231 kB {4} [built]
 [179] multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js 40 bytes {3} [built]
 [201] ./src/root-application/root-application.js 696 bytes {3} [built]
 [421] multi (webpack)-dev-server/client?http://localhost:9090 core-js/client/shim.min.js @angular/common @angular/compiler @angular/core @angular/platform-browser-dynamic @angular/router reflect-metadata react react-dom 136 bytes {4} [built]
 [422] ./node_modules/core-js/client/shim.min.js 87.9 kB {4} [built]
    + 446 hidden modules

WARNING in ./node_modules/@dojo/framework/core/vdom.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/RegistryHandler.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/RegistryHandler.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/diff.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/diff.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/Registry.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/Registry.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/has.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/has.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/Map.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/Map.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/Set.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/Set.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/WeakMap.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/WeakMap.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/global.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/global.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/WidgetBase.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/WidgetBase.js
 @ ./src/dojo/App.ts
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/Evented.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/Evented.js
 @ ./node_modules/@dojo/framework/core/RegistryHandler.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/Promise.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/Promise.js
 @ ./node_modules/@dojo/framework/core/Registry.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/Symbol.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/Symbol.js
 @ ./node_modules/@dojo/framework/shim/Map.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/iterator.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/iterator.js
 @ ./node_modules/@dojo/framework/shim/WeakMap.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/NodeHandler.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/NodeHandler.js
 @ ./node_modules/@dojo/framework/core/WidgetBase.js
 @ ./src/dojo/App.ts
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/object.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/object.js
 @ ./node_modules/@dojo/framework/shim/Map.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/core/Destroyable.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/core/Destroyable.js
 @ ./node_modules/@dojo/framework/core/Evented.js
 @ ./node_modules/@dojo/framework/core/RegistryHandler.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/support/queue.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/support/queue.js
 @ ./node_modules/@dojo/framework/shim/Promise.js
 @ ./node_modules/@dojo/framework/core/Registry.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/support/util.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/support/util.js
 @ ./node_modules/@dojo/framework/shim/Symbol.js
 @ ./node_modules/@dojo/framework/shim/Map.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js

WARNING in ./node_modules/@dojo/framework/shim/string.js
3:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@dojo/framework/shim/string.js
 @ ./node_modules/@dojo/framework/shim/iterator.js
 @ ./node_modules/@dojo/framework/shim/WeakMap.js
 @ ./node_modules/@dojo/framework/core/vdom.js
 @ ./src/dojo/index.js
 @ ./src/root-application/root-application.js
 @ multi (webpack)-dev-server/client?http://localhost:9090 src/root-application/root-application.js
webpack: Compiled with warnings.

```

**Comment by filoxo** [comment] 2020-02-19 06:09
I just noticed that the dojo imports of your index.js are incorrect. They should be 

```js
import { renderer } from '@dojo/framework/core/vdom';
import { v, w } from '@dojo/framework/widget-core/d';
```
As shown in the Quick start code here: https://single-spa.js.org/docs/next/ecosystem-dojo/

**Comment by VigneshRamamoorthy1992** [comment] 2020-02-19 06:23
> I just noticed that the dojo imports of your index.js are incorrect. They should be
> 
> ```js
> import { renderer } from '@dojo/framework/core/vdom';
> import { v, w } from '@dojo/framework/widget-core/d';
> ```
> 
> As shown in the Quick start code here: https://single-spa.js.org/docs/next/ecosystem-dojo/

Thanks!

I made these changes.
still ended up with the same errors.

**Comment by joeldenning** [comment] 2020-02-23 18:56
Ultimately this is a problem specific to your project and webpack configuration. It is not specific to single-spa or single-spa-dojo. You'll have to solve these problems on your own - we won't be able to fix them for you.

Closing this since it does not appear to be an issue with single-spa-dojo. Feel free to comment further or reopen if that's not the case.

**Closed by joeldenning** 2020-02-23 18:56 UTC

**Comment by VigneshRamamoorthy1992** [comment] 2020-02-24 05:21
@joeldenning 
thanks
a small example using `single-spa-dojo` would be much helpful

**Comment by VigneshRamamoorthy1992** [comment] 2020-03-05 09:57
> @joeldenning
> thanks
> a small example using `single-spa-dojo` would be much helpful

could you please update on this.

**Comment by joeldenning** [comment] 2020-03-08 03:44
@VigneshRamamoorthy1992 I don't have the time / energy to create an example for you right now. I am maxed out on how much open source work I can do.

**Comment by tacnoman** [comment] 2021-07-01 21:24
Same problem here. I just runned `npx create-single-spa` and when I try to run I receive this error :/
The create-single-app created with these versions:

```json
    "webpack-config-single-spa-react": "^2.2.2",
    "webpack-dev-server": "^4.0.0-beta.0",
```

This error happens when I run: `http://single-spa-playground.org/playground/instant-test?name=@company/component&url=8500`

I exported these three lines too:

```js
export const bootstrap = lifecycles.bootstrap;
export const mount = lifecycles.mount;
export const unmount = lifecycles.unmount;
```

Someone can help me?

**Comment by joeldenning** [comment] 2021-07-04 00:09
I cannot reproduce the problem, having created a new project with create-single-spa and trying it out. Please provide a demonstration and create a new issue.
